version: '3'

services:
  airu1:
    image: crossfw/airu
    container_name: airu1
    restart: always
    network_mode: host
    volumes:
      - ./airu.json:/etc/au/config.json
      - ./cert/:/usr/local/share/au/
      - ./xray-log/xray.log:/var/log/xray.log
  xray-airu:
    image: teddysun/xray
    container_name: xray-airu
    restart: always
    network_mode: host
    volumes:
    - ./xray.json:/etc/xray/config.json
    - ./xray-log/xray.log:/var/log/xray.log
